package com.google.android.gms.internal.ads;

import android.content.pm.ApplicationInfo;
import android.content.pm.PackageInfo;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.daaw.C4826gP1;
import com.daaw.JM0;
import com.google.android.gms.ads.internal.client.zzdu;
import com.google.android.gms.ads.internal.client.zzl;
import com.google.android.gms.ads.internal.client.zzq;
import com.google.android.gms.common.internal.safeparcel.AbstractSafeParcelable;
import j$.util.DesugarCollections;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: loaded from: classes3.dex */
public final class zzbuh extends AbstractSafeParcelable {
    public static final Parcelable.Creator<zzbuh> CREATOR = new C4826gP1();
    public final boolean A0;
    public final int B;
    public final boolean B0;
    public final Bundle C;
    public final ArrayList C0;
    public final zzl D;
    public final String D0;
    public final zzq E;
    public final zzbls E0;
    public final String F;
    public final String F0;
    public final ApplicationInfo G;
    public final Bundle G0;
    public final PackageInfo H;
    public final String I;
    public final String J;
    public final String K;
    public final zzcaz L;
    public final Bundle M;
    public final int N;
    public final List O;
    public final Bundle P;
    public final boolean Q;
    public final int R;
    public final int S;
    public final float T;
    public final String U;
    public final long V;
    public final String W;
    public final List X;
    public final String Y;
    public final zzbfc Z;
    public final List a0;
    public final long b0;
    public final String c0;
    public final float d0;
    public final int e0;
    public final int f0;
    public final boolean g0;
    public final String h0;
    public final boolean i0;
    public final String j0;
    public final boolean k0;
    public final int l0;
    public final Bundle m0;
    public final String n0;
    public final zzdu o0;
    public final boolean p0;
    public final Bundle q0;
    public final String r0;
    public final String s0;
    public final String t0;
    public final boolean u0;
    public final List v0;
    public final String w0;
    public final List x0;
    public final int y0;
    public final boolean z0;

    public zzbuh(int i, Bundle bundle, zzl zzlVar, zzq zzqVar, String str, ApplicationInfo applicationInfo, PackageInfo packageInfo, String str2, String str3, String str4, zzcaz zzcazVar, Bundle bundle2, int i2, List list, Bundle bundle3, boolean z, int i3, int i4, float f, String str5, long j, String str6, List list2, String str7, zzbfc zzbfcVar, List list3, long j2, String str8, float f2, boolean z2, int i5, int i6, boolean z3, String str9, String str10, boolean z4, int i7, Bundle bundle4, String str11, zzdu zzduVar, boolean z5, Bundle bundle5, String str12, String str13, String str14, boolean z6, List list4, String str15, List list5, int i8, boolean z7, boolean z8, boolean z9, ArrayList arrayList, String str16, zzbls zzblsVar, String str17, Bundle bundle6) {
        this.B = i;
        this.C = bundle;
        this.D = zzlVar;
        this.E = zzqVar;
        this.F = str;
        this.G = applicationInfo;
        this.H = packageInfo;
        this.I = str2;
        this.J = str3;
        this.K = str4;
        this.L = zzcazVar;
        this.M = bundle2;
        this.N = i2;
        this.O = list;
        this.a0 = list3 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list3);
        this.P = bundle3;
        this.Q = z;
        this.R = i3;
        this.S = i4;
        this.T = f;
        this.U = str5;
        this.V = j;
        this.W = str6;
        this.X = list2 == null ? Collections.EMPTY_LIST : DesugarCollections.unmodifiableList(list2);
        this.Y = str7;
        this.Z = zzbfcVar;
        this.b0 = j2;
        this.c0 = str8;
        this.d0 = f2;
        this.i0 = z2;
        this.e0 = i5;
        this.f0 = i6;
        this.g0 = z3;
        this.h0 = str9;
        this.j0 = str10;
        this.k0 = z4;
        this.l0 = i7;
        this.m0 = bundle4;
        this.n0 = str11;
        this.o0 = zzduVar;
        this.p0 = z5;
        this.q0 = bundle5;
        this.r0 = str12;
        this.s0 = str13;
        this.t0 = str14;
        this.u0 = z6;
        this.v0 = list4;
        this.w0 = str15;
        this.x0 = list5;
        this.y0 = i8;
        this.z0 = z7;
        this.A0 = z8;
        this.B0 = z9;
        this.C0 = arrayList;
        this.D0 = str16;
        this.E0 = zzblsVar;
        this.F0 = str17;
        this.G0 = bundle6;
    }

    @Override // android.os.Parcelable
    public final void writeToParcel(Parcel parcel, int i) {
        int i2 = this.B;
        int iA = JM0.a(parcel);
        JM0.k(parcel, 1, i2);
        JM0.e(parcel, 2, this.C, false);
        JM0.p(parcel, 3, this.D, i, false);
        JM0.p(parcel, 4, this.E, i, false);
        JM0.q(parcel, 5, this.F, false);
        JM0.p(parcel, 6, this.G, i, false);
        JM0.p(parcel, 7, this.H, i, false);
        JM0.q(parcel, 8, this.I, false);
        JM0.q(parcel, 9, this.J, false);
        JM0.q(parcel, 10, this.K, false);
        JM0.p(parcel, 11, this.L, i, false);
        JM0.e(parcel, 12, this.M, false);
        JM0.k(parcel, 13, this.N);
        JM0.s(parcel, 14, this.O, false);
        JM0.e(parcel, 15, this.P, false);
        JM0.c(parcel, 16, this.Q);
        JM0.k(parcel, 18, this.R);
        JM0.k(parcel, 19, this.S);
        JM0.h(parcel, 20, this.T);
        JM0.q(parcel, 21, this.U, false);
        JM0.n(parcel, 25, this.V);
        JM0.q(parcel, 26, this.W, false);
        JM0.s(parcel, 27, this.X, false);
        JM0.q(parcel, 28, this.Y, false);
        JM0.p(parcel, 29, this.Z, i, false);
        JM0.s(parcel, 30, this.a0, false);
        JM0.n(parcel, 31, this.b0);
        JM0.q(parcel, 33, this.c0, false);
        JM0.h(parcel, 34, this.d0);
        JM0.k(parcel, 35, this.e0);
        JM0.k(parcel, 36, this.f0);
        JM0.c(parcel, 37, this.g0);
        JM0.q(parcel, 39, this.h0, false);
        JM0.c(parcel, 40, this.i0);
        JM0.q(parcel, 41, this.j0, false);
        JM0.c(parcel, 42, this.k0);
        JM0.k(parcel, 43, this.l0);
        JM0.e(parcel, 44, this.m0, false);
        JM0.q(parcel, 45, this.n0, false);
        JM0.p(parcel, 46, this.o0, i, false);
        JM0.c(parcel, 47, this.p0);
        JM0.e(parcel, 48, this.q0, false);
        JM0.q(parcel, 49, this.r0, false);
        JM0.q(parcel, 50, this.s0, false);
        JM0.q(parcel, 51, this.t0, false);
        JM0.c(parcel, 52, this.u0);
        JM0.m(parcel, 53, this.v0, false);
        JM0.q(parcel, 54, this.w0, false);
        JM0.s(parcel, 55, this.x0, false);
        JM0.k(parcel, 56, this.y0);
        JM0.c(parcel, 57, this.z0);
        JM0.c(parcel, 58, this.A0);
        JM0.c(parcel, 59, this.B0);
        JM0.s(parcel, 60, this.C0, false);
        JM0.q(parcel, 61, this.D0, false);
        JM0.p(parcel, 63, this.E0, i, false);
        JM0.q(parcel, 64, this.F0, false);
        JM0.e(parcel, 65, this.G0, false);
        JM0.b(parcel, iA);
    }
}
