package com.daaw;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/* JADX INFO: renamed from: com.daaw.yG, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes3.dex */
public abstract class AbstractC9826yG {
    public static List a(String str) {
        int length = str.length();
        AbstractC6557mb.d(length >= 2, "Invalid path \"%s\"", str);
        if (length == 2) {
            AbstractC6557mb.d(str.charAt(0) == 1 && str.charAt(1) == 1, "Non-empty path \"%s\" had length 2", str);
            return Collections.EMPTY_LIST;
        }
        int length2 = str.length() - 2;
        ArrayList arrayList = new ArrayList();
        StringBuilder sb = new StringBuilder();
        int i = 0;
        while (i < length) {
            int iIndexOf = str.indexOf(1, i);
            if (iIndexOf < 0 || iIndexOf > length2) {
                throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
            }
            int i2 = iIndexOf + 1;
            char cCharAt = str.charAt(i2);
            if (cCharAt == 1) {
                String strSubstring = str.substring(i, iIndexOf);
                if (sb.length() != 0) {
                    sb.append(strSubstring);
                    strSubstring = sb.toString();
                    sb.setLength(0);
                }
                arrayList.add(strSubstring);
            } else if (cCharAt == 16) {
                sb.append(str.substring(i, iIndexOf));
                sb.append((char) 0);
            } else {
                if (cCharAt != 17) {
                    throw new IllegalArgumentException("Invalid encoded resource path: \"" + str + "\"");
                }
                sb.append(str.substring(i, i2));
            }
            i = iIndexOf + 2;
        }
        return arrayList;
    }

    public static UI0 b(String str) {
        return UI0.t(a(str));
    }

    public static String c(AbstractC0840Fe abstractC0840Fe) {
        StringBuilder sb = new StringBuilder();
        int iP = abstractC0840Fe.p();
        for (int i = 0; i < iP; i++) {
            if (sb.length() > 0) {
                e(sb);
            }
            d(abstractC0840Fe.m(i), sb);
        }
        e(sb);
        return sb.toString();
    }

    public static void d(String str, StringBuilder sb) {
        int length = str.length();
        for (int i = 0; i < length; i++) {
            char cCharAt = str.charAt(i);
            if (cCharAt == 0) {
                sb.append((char) 1);
                sb.append((char) 16);
            } else if (cCharAt != 1) {
                sb.append(cCharAt);
            } else {
                sb.append((char) 1);
                sb.append((char) 17);
            }
        }
    }

    public static void e(StringBuilder sb) {
        sb.append((char) 1);
        sb.append((char) 1);
    }

    public static String f(String str) {
        StringBuilder sb = new StringBuilder(str);
        int length = sb.length() - 1;
        char cCharAt = sb.charAt(length);
        AbstractC6557mb.d(cCharAt == 1, "successor may only operate on paths generated by encode", new Object[0]);
        sb.setCharAt(length, (char) (cCharAt + 1));
        return sb.toString();
    }
}
