package com.daaw;

/* JADX INFO: renamed from: com.daaw.Rs0, reason: case insensitive filesystem */
/* JADX INFO: loaded from: classes4.dex */
public interface InterfaceC2166Rs0 {

    /* JADX INFO: renamed from: com.daaw.Rs0$a */
    public static final class a {
        public static Object[] a(InterfaceC2166Rs0 interfaceC2166Rs0, int i) {
            throw new C0673Do0("Generated by Android Extensions automatically");
        }
    }
}
