plugins {
    id 'com.android.application'
}

android {
	namespace "com.daaw.avee"
    compileSdkVersion 36

    defaultConfig {
        applicationId 'com.daaw.avee'
        minSdkVersion 21
        //noinspection ExpiringTargetSdkVersion,ExpiredTargetSdkVersion
        targetSdkVersion 36
        versionCode 252
        versionName "1.2.252"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }

    buildFeatures {
        buildConfig = false
    }
}

dependencies {
    // TODO: dependencies
}
