package com.android.billingclient.api;

import com.android.billingclient.api.d;

/* JADX INFO: loaded from: classes.dex */
public abstract class i {
    public static final d A;
    public static final d B;
    public static final d C;
    public static final d D;
    public static final d E;
    public static final d F;
    public static final d a;
    public static final d b;
    public static final d c;
    public static final d d;
    public static final d e;
    public static final d f;
    public static final d g;
    public static final d h;
    public static final d i;
    public static final d j;
    public static final d k;
    public static final d l;
    public static final d m;
    public static final d n;
    public static final d o;
    public static final d p;
    public static final d q;
    public static final d r;
    public static final d s;
    public static final d t;
    public static final d u;
    public static final d v;
    public static final d w;
    public static final d x;
    public static final d y;
    public static final d z;

    static {
        d.a aVarC = d.c();
        aVarC.c(3);
        aVarC.b("Google Play In-app Billing API version is less than 3");
        a = aVarC.a();
        d.a aVarC2 = d.c();
        aVarC2.c(3);
        aVarC2.b("Google Play In-app Billing API version is less than 9");
        b = aVarC2.a();
        d.a aVarC3 = d.c();
        aVarC3.c(3);
        aVarC3.b("Billing service unavailable on device.");
        c = aVarC3.a();
        d.a aVarC4 = d.c();
        aVarC4.c(5);
        aVarC4.b("Client is already in the process of connecting to billing service.");
        d = aVarC4.a();
        d.a aVarC5 = d.c();
        aVarC5.c(5);
        aVarC5.b("The list of SKUs can't be empty.");
        e = aVarC5.a();
        d.a aVarC6 = d.c();
        aVarC6.c(5);
        aVarC6.b("SKU type can't be empty.");
        f = aVarC6.a();
        d.a aVarC7 = d.c();
        aVarC7.c(5);
        aVarC7.b("Product type can't be empty.");
        g = aVarC7.a();
        d.a aVarC8 = d.c();
        aVarC8.c(-2);
        aVarC8.b("Client does not support extra params.");
        h = aVarC8.a();
        d.a aVarC9 = d.c();
        aVarC9.c(5);
        aVarC9.b("Invalid purchase token.");
        i = aVarC9.a();
        d.a aVarC10 = d.c();
        aVarC10.c(6);
        aVarC10.b("An internal error occurred.");
        j = aVarC10.a();
        d.a aVarC11 = d.c();
        aVarC11.c(5);
        aVarC11.b("SKU can't be null.");
        k = aVarC11.a();
        d.a aVarC12 = d.c();
        aVarC12.c(0);
        l = aVarC12.a();
        d.a aVarC13 = d.c();
        aVarC13.c(-1);
        aVarC13.b("Service connection is disconnected.");
        m = aVarC13.a();
        d.a aVarC14 = d.c();
        aVarC14.c(2);
        aVarC14.b("Timeout communicating with service.");
        n = aVarC14.a();
        d.a aVarC15 = d.c();
        aVarC15.c(-2);
        aVarC15.b("Client does not support subscriptions.");
        o = aVarC15.a();
        d.a aVarC16 = d.c();
        aVarC16.c(-2);
        aVarC16.b("Client does not support subscriptions update.");
        p = aVarC16.a();
        d.a aVarC17 = d.c();
        aVarC17.c(-2);
        aVarC17.b("Client does not support get purchase history.");
        q = aVarC17.a();
        d.a aVarC18 = d.c();
        aVarC18.c(-2);
        aVarC18.b("Client does not support price change confirmation.");
        r = aVarC18.a();
        d.a aVarC19 = d.c();
        aVarC19.c(-2);
        aVarC19.b("Play Store version installed does not support cross selling products.");
        s = aVarC19.a();
        d.a aVarC20 = d.c();
        aVarC20.c(-2);
        aVarC20.b("Client does not support multi-item purchases.");
        t = aVarC20.a();
        d.a aVarC21 = d.c();
        aVarC21.c(-2);
        aVarC21.b("Client does not support offer_id_token.");
        u = aVarC21.a();
        d.a aVarC22 = d.c();
        aVarC22.c(-2);
        aVarC22.b("Client does not support ProductDetails.");
        v = aVarC22.a();
        d.a aVarC23 = d.c();
        aVarC23.c(-2);
        aVarC23.b("Client does not support in-app messages.");
        w = aVarC23.a();
        d.a aVarC24 = d.c();
        aVarC24.c(-2);
        aVarC24.b("Client does not support user choice billing.");
        x = aVarC24.a();
        d.a aVarC25 = d.c();
        aVarC25.c(-2);
        aVarC25.b("Play Store version installed does not support external offer.");
        y = aVarC25.a();
        d.a aVarC26 = d.c();
        aVarC26.c(5);
        aVarC26.b("Unknown feature");
        z = aVarC26.a();
        d.a aVarC27 = d.c();
        aVarC27.c(-2);
        aVarC27.b("Play Store version installed does not support get billing config.");
        A = aVarC27.a();
        d.a aVarC28 = d.c();
        aVarC28.c(-2);
        aVarC28.b("Query product details with serialized docid is not supported.");
        B = aVarC28.a();
        d.a aVarC29 = d.c();
        aVarC29.c(4);
        aVarC29.b("Item is unavailable for purchase.");
        C = aVarC29.a();
        d.a aVarC30 = d.c();
        aVarC30.c(-2);
        aVarC30.b("Query product details with developer specified account is not supported.");
        D = aVarC30.a();
        d.a aVarC31 = d.c();
        aVarC31.c(-2);
        aVarC31.b("Play Store version installed does not support alternative billing only.");
        E = aVarC31.a();
        d.a aVarC32 = d.c();
        aVarC32.c(5);
        aVarC32.b("To use this API you must specify a PurchasesUpdateListener when initializing a BillingClient.");
        F = aVarC32.a();
    }

    public static d a(int i2, String str) {
        d.a aVarC = d.c();
        aVarC.c(i2);
        aVarC.b(str);
        return aVarC.a();
    }
}
